### ISSUE TITLE
skill does not load

### ISSUE THREAD

**Issue by domcross** [MycroftAI/skill-iot-control#1]
skill does not load on Mycroft 19.2.1 on a Mark-1:
```
00:28:20.545 - mycroft.skills.core:load_skill:166 - ERROR - Failed to load skill: skill-iot-control.domcross
Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/mycroft/skills/core.py", line 128, in load_skill
    imp.PY_SOURCE))
  File "/opt/venvs/mycroft-core/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/opt/venvs/mycroft-core/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/opt/mycroft/skills/skill-iot-control.domcross/__init__.py", line 20, in <module>
    from mycroft.skills.common_iot_skill import \
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/mycroft/skills/common_iot_skill.py", line 22, in <module>
    from enum import Enum, unique, auto
ImportError: cannot import name 'auto'
```

**Comment by penrods** [comment]
Yeah, we should avoid using ```enum.auto```, it doesn't exist in Python 3.4.  I don't really see any advantage to just explicitly typing in values for this small of a list.  Just add a comment telling future implementors that the values MUST be unique.

**Comment by domcross** [comment]
found a [workaround](https://codereview.stackexchange.com/questions/177309/reimplementing-pythons-enum-auto-for-compatibility) for this issue. Will perform some test and file a PR...

**Comment by ChristopherRogers1991** [comment]
This was resolved by https://github.com/MycroftAI/mycroft-core/pull/2063. Closing this out.
