### ISSUE TITLE
ERROR - Failed to load skill: skill-iot-control.mycroftai

### ISSUE THREAD

**Issue by scottsweb** [MycroftAI/skill-iot-control#6]
Attempting to use this skill and seeing the following error:

```
Traceback (most recent call last):
  File "/opt/mycroft/mycroft/skills/core.py", line 131, in load_skill
    imp.PY_SOURCE))
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/opt/mycroft/skills/skill-iot-control.mycroftai/__init__.py", line 63
    self.speech_requests: DefaultDict[str, List[SpeechRequest]] = defaultdict(list)
                        ^
SyntaxError: invalid syntax
```

Python 3.5.2.
Mycroft 19.2.13

I am seeing a similar error with the Home Assistant skill (which is why I need this skill). Is this a Python version issue?

**Comment by scottsweb** [comment]
I managed to fix this by upgrading Python to 3.7.4
